substitutions:
  devicename: led-kitchen
  leds: 142
  supply_voltage: 5.0

esphome:
  name: ${devicename}
  friendly_name: LED cucina 1

esp8266:
  board: d1_mini
  restore_from_flash: true

logger: null

api:
  encryption:
    key: y1uji+dYTBa4Yw/wkoBripP25oka7wodVTnVmbmUMXU=

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_password_2
  ap:
    ssid: ${devicename} Fallback Hotspot
    password: yK4Nia32K90Z

ota:
- platform: esphome
  password: 6e8a5724f0642b7e239e4a42e6786942

captive_portal: null

web_server:
  local: true
  version: 3

globals:
  - id: led_ma_per_channel
    type: float
    restore_value: no
    initial_value: "20.0"
  - id: idle_ma_per_led
    type: float
    restore_value: no
    initial_value: "0.8"
  - id: overhead_factor
    type: float
    restore_value: no
    initial_value: "1.10"

light:
- platform: neopixelbus
  restore_mode: RESTORE_DEFAULT_ON
  variant: WS2812
  pin: D4
  num_leds: ${leds}
  type: GRB
  name: NeoPixel WS2812
  id: light1
  icon: mdi:led-strip-variant
  effects:
  - strobe: null
  - flicker: null
  - addressable_rainbow: null
  - addressable_color_wipe: null
  - addressable_scan: null
  - addressable_twinkle: null
  - addressable_random_twinkle: null
  - addressable_fireworks: null

text_sensor:
- platform: wifi_info
  ip_address:
    name: ${devicename} IP address
    icon: mdi:wifi
    entity_category: diagnostic
  ssid:
    name: ${devicename} SSID
    icon: mdi:wifi
    entity_category: diagnostic
  bssid:
    name: ${devicename} BSSID
    icon: mdi:wifi
    entity_category: diagnostic
  mac_address:
    name: ${devicename} MAC address
    icon: mdi:chip
    entity_category: diagnostic
    
sensor:
- platform: wifi_signal
  name: ${devicename} WiFi Signal
  id: wifi_signal_db
  entity_category: diagnostic
  device_class: signal_strength
  icon: mdi:wifi
- platform: uptime
  name: ${devicename} Uptime
  icon: mdi:clock
  device_class: duration
- platform: template
  id: led_est_current
  name: "Corrente stimata"
  unit_of_measurement: "A"
  device_class: current
  accuracy_decimals: 2
  update_interval: 10s
  lambda: |-
    using esphome::light::LightColorValues;
    auto &cv = id(light1).current_values;

    float b  = cv.get_brightness();   // 0..1
    float r  = cv.get_red()   * b;
    float g  = cv.get_green() * b;
    float bl = cv.get_blue()  * b;

    const float channels_sum = r + g + bl; // 0..3
    const float ma_per_led   = channels_sum * id(led_ma_per_channel) + id(idle_ma_per_led);
    const float total_ma     = (${leds} * ma_per_led) * id(overhead_factor);

    return total_ma / 1000.0f; // Ampere

- platform: template
  name: "LED Potenza stimata"
  unit_of_measurement: "W"
  device_class: power
  accuracy_decimals: 1
  update_interval: 60s
  lambda: |-
    return id(led_est_current).state * ${supply_voltage};   

number:
  - platform: template
    name: "mA per canale"
    min_value: 10
    max_value: 25
    step: 0.5
    optimistic: true
    initial_value: 20
    set_action:
      then:
        - lambda: |-
            id(led_ma_per_channel) = x;
  - platform: template
    name: "mA idle per LED"
    min_value: 0.1
    max_value: 2
    step: 0.1
    optimistic: true
    initial_value: 0.8
    set_action:
      then:
        - lambda: |-
            id(idle_ma_per_led) = x;
  - platform: template
    name: "Overhead factor"
    min_value: 1.00
    max_value: 1.30
    step: 0.01
    optimistic: true
    initial_value: 1.10
    set_action:
      then:
        - lambda: |-
            id(overhead_factor) = x;