substitutions:
  devicename: pir-light-sensor

esphome:
  name: ${devicename}
  friendly_name: PIR sensore luce

esp8266:
  board: d1_mini_pro

logger: null

api:
  encryption:
    key: w1/7Ba7TqBAe7MUqB92PP9G0k2r0aGg3s3clxtW6iZU=

wifi:
  ssid: !secret wifi_ssid_24GHz
  password: !secret wifi_password_24GHz
  ap:
    ssid: ${devicename} Fb Hs
    password: yK4Nia32K90Z

ota:
  platform: esphome
  password: 2b417d49beeb6d721f64d006161ec80d

captive_portal: null

web_server:
  local: true

i2c:
  sda: 4
  scl: 5
  scan: true

text_sensor:
- platform: wifi_info
  ip_address:
    name: ${devicename} IP address
    icon: mdi:access-point-network
  ssid:
    name: ${devicename} SSID
    icon: mdi:access-point-network
  bssid:
    name: ${devicename} BSSID
    icon: mdi:access-point-network
  mac_address:
    name: ${devicename} MAC address
    icon: mdi:chip

sensor:
- platform: wifi_signal
  name: ${devicename} WiFi Signal
  id: wifi_signal_db
  entity_category: diagnostic
  device_class: signal_strength
  icon: mdi:wifi
  update_interval: 60s
- platform: uptime
  name: ${devicename} Uptime
  icon: mdi:clock
  device_class: duration
  update_interval: 60s
- platform: bh1750
  name: BH1750
  address: 35
  update_interval: 1s
  device_class: illuminance
  filters:
  - delta: 10%

switch:
  - platform: restart
    name: ${devicename} restart
    device_class: switch
    entity_category: diagnostic    