substitutions:
  devicename: 2d-matrix
  ledpin: GPIO02
  board: wemos_d1_mini32
  loglevel: DEBUG
  xscrollpadding: "4"
  xscrollingspeed: "10"
  huerotatespeed: "1"
  yoffset: "1"
  basetopic: matrix

esphome:
  name: 2d-matrix
  friendly_name: 2D-Matrix
  includes: 
    - hsv.h  

esp32:
  board: $board
  framework:
    type: arduino

# Enable logging
logger:
  # level: $loglevel

# Enable Home Assistant API
api:
  encryption:
    key: "7vElxNdvfqnfD4QmcCA24bRfSX46wKNh99P+AZKov8I="

ota:
  password: "336695593db2943812ee9a426b0493d5"

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_password_2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "2D-Matrix Fallback Hotspot"
    password: "eNVCkfroNshU"

captive_portal:
    
web_server:
  port: 80

font:
  - id: tinyfont
    file: fonts/pixelart.ttf
    size: 8
    glyphs: '♡àèéìòù!"%()+,-_.:*=°?~#0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
  - file:
      type: gfonts
      family: Roboto
      weight: 300
    id: Roboto_Condensed
    size: 8

time:
  - platform: sntp
    id: rtctime
    on_time:
      - seconds: /$huerotatespeed
        then:
          - lambda: |-
              const int hue_rotate_speed = id(my_global_hue_rotate_speed);
              if (hue_rotate_speed != 0) {
                if (id(my_global_hue) < 360) {
                  id(my_global_hue) += 1;
                } else {
                  id(my_global_hue) = 0;
                }
                // ESP_LOGD("time.lambda", "my_global_hue %i", id(my_global_hue));
              }
      - seconds: /$xscrollingspeed
        then:
          - lambda: |-
              if (id(my_global_scroll) < 360) {
                id(my_global_scroll) += 1;
              } else {
                id(my_global_scroll) = 0;
              }                 
    
mqtt:
  id: mqtt_client
  broker: !secret mqtt_broker
  username: !secret mqtt_user 
  password: !secret mqtt_password
  on_json_message:
    topic: $devicename/$basetopic/hue_json
    then:
      - lambda: |-
          if (x.containsKey("hue_rotate")) {
            const byte hue_rotate = x["hue_rotate"];
            id(my_global_hue_rotate) = hue_rotate;
            ESP_LOGI("mqtt.json", "hue_rotate %i", hue_rotate);              
          }
          if (x.containsKey("hue_rotate_speed")) {
            const byte hue_rotate_speed = x["hue_rotate_speed"];
            id(my_global_hue_rotate_speed) = hue_rotate_speed;
            ESP_LOGI("mqtt.json", "hue_rotate_speed %i", hue_rotate_speed);              
          }
          if (x.containsKey("HSV")) {
            int HSV[3];
            HSV[0] = x["HSV"][0];
            HSV[1] = x["HSV"][1];
            HSV[2] = x["HSV"][2];
            id(my_global_hsv)[0] = HSV[0];
            id(my_global_hsv)[1] = HSV[1];
            id(my_global_hsv)[2] = HSV[2];
            id(my_global_hue) = HSV[0];
            ESP_LOGI("mqtt.json", "HSV %i,%i,%i", HSV[0],HSV[1],HSV[2]);
          }          
          if (x.containsKey("hue")) {
            const byte hue = x["hue"];
            ESP_LOGI("mqtt.json", "hue %i", hue);
          }
          if (x.containsKey("saturation")) {
            const byte saturation = x["saturation"];
            ESP_LOGI("mqtt.json", "saturation %i", saturation);
          }           
          if (x.containsKey("value")) {
            const byte value = x["value"];
            ESP_LOGI("mqtt.json", "value %i", value);
          }                      
          if (x.containsKey("RGB")) {
            byte RGB[3];
            RGB[0] = x["RGB"][0];
            RGB[1] = x["RGB"][1];
            RGB[2] = x["RGB"][2];
            id(my_global_rgb)[0] = RGB[0];
            id(my_global_rgb)[1] = RGB[1];
            id(my_global_rgb)[2] = RGB[2];
            ESP_LOGI("mqtt.json", "RGB %i,%i,%i", RGB[0],RGB[1],RGB[2]);
            unsigned long myrgb = (RGB[0]<<16) | (RGB[1]<<8) | RGB[2]; 
            id(text_color).publish_state(myrgb);   
            char myrgb_hex[8];
            snprintf(myrgb_hex, 8, "0x%X;", myrgb);
            id(text_color_hex).publish_state(myrgb_hex);            
          }
          if (x.containsKey("HEX")) {
            const char *HEXA = x["HEX"];
            id(my_global_textcolor) = HEXA;
            ESP_LOGI("mqtt.json", "HEX %s", HEXA);
            unsigned long myrgb = (int)strtol(HEXA, NULL, 0);             
            id(text_color).publish_state(myrgb);    
            id(text_color_hex).publish_state(HEXA);           
          }
          if (x.containsKey("text")) {
            const char *text = x["text"];
            id(my_global_text) = text;
            ESP_LOGI("mqtt.json", "text %s", text);
          }                  
              
globals:
  - id: my_global_hue
    type: int
    restore_value: no
    initial_value: '0'
  - id: my_global_scroll
    type: int
    restore_value: no
    initial_value: '0'
  - id: my_global_hue_rotate
    type: int
    restore_value: no
    initial_value: '0'
  - id: my_global_hue_rotate_speed
    type: int
    restore_value: no
    initial_value: '1'    
  - id: my_global_hsv
    type: int[3]
    restore_value: no
  - id: my_global_rgb
    type: byte[3]
    restore_value: no    
  - id: my_global_textcolor
    type: std::string
    restore_value: no
    initial_value: "{'0','x','A','A','1','1','1','1'}" 
  - id: my_global_text
    type: std::string
    restore_value: no
    initial_value: "{'H','e','l','l','o',' ','W','o','r','l','d'}"     
   

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: ipaddress
      icon: mdi:web
    ssid:
      name: ESP Connected SSID
      icon: mdi:wifi
    bssid:
      name: ESP Connected BSSID
      icon: mdi:wifi
    mac_address:
      name: ESP Mac Wifi Address
      icon: mdi:chip
    scan_results:
      name: ESP Latest Scan Results    
      icon: mdi:wifi
  - platform: template
    name: "Text color"
    id: text_color_hex
    lambda: |-
      unsigned long myrgb;
      if (id(my_global_hue_rotate) != 1) {
        const char * textcolor = id(my_global_textcolor).c_str();
        myrgb = (int)strtol(textcolor, NULL, 0); 
      } else {
        myrgb = (id(my_global_rgb)[0]<<16) | (id(my_global_rgb)[1]<<8) | id(my_global_rgb)[2]; 
      }
      char myrgb_hex[8];
      snprintf(myrgb_hex, 8, "0x%X;", myrgb);
      std::string myrgb_hex_str = myrgb_hex;
      return myrgb_hex_str;
    # update_interval: 1s      

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s    
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
  - platform: template
    name: "Text color"
    id: text_color
    lambda: |-
      unsigned long myrgb;
      if (id(my_global_hue_rotate) != 1) {
        const char * textcolor = id(my_global_textcolor).c_str();
        myrgb = (int)strtol(textcolor, NULL, 0); 
      } else {
        myrgb = (id(my_global_rgb)[0]<<16) | (id(my_global_rgb)[1]<<8) | id(my_global_rgb)[2]; 
      }
      return myrgb;
    # update_interval: 1s
  - platform: template
    name: "Hue rotate speed"
    lambda: |-
      return int(id(my_global_hue_rotate_speed));
    # update_interval: 1s
  - platform: template
    name: "Hue"
    lambda: |-
      return int(id(my_global_hue));
    # update_interval: 1s
  - platform: template
    name: "Scroll"
    lambda: |-
      return int(id(my_global_scroll));
    # update_interval: 1s  
  - platform: template
    name: "Hue rotate"
    lambda: |-
      return int(id(my_global_hue_rotate));
    # update_interval: 1s        

e131:
  method: multicast

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: $ledpin
    num_leds: 64
    name: "$devicename Light"
    id: mylight
    icon: mdi:led-strip-variant
    # color_correct: [40%, 40%, 40%]
    effects:
      - e131:
          universe: 1
          channels: RGB
   
display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: mylight
    width: 8
    height: 8
    rotation: 0°
    # pixel_mapper: |-
    #   if (x % 2 == 0) {
    #     return (x * 8) + y;
    #   }
    #   return (x * 8) + (7 - y);
    update_interval: 200ms
    lambda: |-
      // static uint16_t xpos = 0;
      int x_pos_global = id(my_global_scroll);
      byte huerotate_enable = id(my_global_hue_rotate);
      // ESP_LOGD("display.lambda", "huerotate_enable %i", huerotate_enable);
      byte huerotate_speed = id(my_global_hue_rotate_speed);
      // ESP_LOGD("display.lambda", "huerotate_speed %i", huerotate_speed);

      int x_start, y_start;
      int width, height;

      const char * text = id(my_global_text).c_str();
      // ESP_LOGD("display.lambda", "text %i", text); 
      const char * textcolor = id(my_global_textcolor).c_str();
      // ESP_LOGD("display.lambda", "textcolor %i", textcolor);   
      int textcolor_number = (int)strtol(textcolor, NULL, 0);        
  
      int H = id(my_global_hsv)[0];
      if (huerotate_enable == 1) {
        H = id(my_global_hue);
      } 
      byte S = id(my_global_hsv)[1];
      byte V = id(my_global_hsv)[2];      
      // ESP_LOGD("display.lambda", "HSV %i,%i,%i", H,S,V);

      float s = S/100.0;
      float v = V/100.0;
      float C = s*v;
      float X = C*(1-abs(fmod(H/60.0, 2)-1));
      float m = v-C;
      // ESP_LOGD("display.lambda", "s %.2f, v %.2f, C %.2f, X %.2f, m %.2f", s,v,C,X,m);
      float r,g,b;
      if (H >= 0 && H < 60) {
          r = C,g = X,b = 0;
      } else if(H >= 60 && H < 120) {
          r = X,g = C,b = 0;
      } else if(H >= 120 && H < 180) {
          r = 0,g = C,b = X;
      } else if(H >= 180 && H < 240) {
          r = 0,g = X,b = C;
      } else if(H >= 240 && H < 300) {
          r = X,g = 0,b = C;
      } else {
          r = C,g = 0,b = X;
      }
      byte R = (r+m)*255;
      byte G = (g+m)*255;
      byte B = (b+m)*255;
      // ESP_LOGD("display.lambda", "RGB %i,%i,%i", R,G,B);

      it.get_text_bounds(0, 0, text, id(tinyfont), TextAlign::BOTTOM_LEFT, &x_start, &y_start, &width, &height); 
      if (huerotate_enable == 1) {
        it.print(-(x_pos_global % (width + $xscrollpadding)), $yoffset, id(tinyfont), Color(R, G, B), TextAlign::TOP_LEFT, text); 
      } else {
        it.print(-(x_pos_global % (width + $xscrollpadding)), $yoffset, id(tinyfont), Color(textcolor_number), TextAlign::TOP_LEFT, text); 
      }
      
      if (huerotate_speed == 0) {
        if (id(my_global_hue) < 360) {
          id(my_global_hue) += 1;
        } else {
          id(my_global_hue) = 0;
        }
      }   
      
      if (width > it.get_width()) // only scroll if nesessary
        x_pos_global++;
      else
        x_pos_global = 0;
      id(my_global_scroll) = x_pos_global;
