substitutions:
  devicename: amg8833

esphome:
  name: ${devicename}
  platformio_options:
    lib_deps:
      - https://github.com/adafruit/Adafruit_AMG88xx.git
      - https://github.com/adafruit/Adafruit_BusIO.git
      - https://github.com/adafruit/Adafruit_Sensor.git
    lib_ldf_mode: deep+
  includes:
    - amg8833_component.h   # <--- il nostro header C++

esp8266:
  board: d1_mini

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid_24GHz
  password: !secret wifi_password_24GHz

i2c:
  sda: 4
  scl: 5
  frequency: 100kHz
  scan: true

# --- Info WiFi --------------------------------------------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${devicename} IP address
      icon: mdi:access-point-network
    ssid:
      name: ${devicename} SSID
      icon: mdi:access-point-network
    bssid:
      name: ${devicename} BSSID
      icon: mdi:access-point-network
    mac_address:
      name: ${devicename} MAC address
      icon: mdi:chip

  # matrice termica come CSV (8x8, interi, max 255 char)
  - platform: custom
    lambda: |-
      auto cam = new AMG8833CameraComponent();
      App.register_component(cam);
      return { cam->sensor_pixels };
    text_sensors:
      - name: ${devicename} sensor pixels
        icon: mdi:grid

# --- Sensori numerici -------------------------------------------------------
sensor:
  - platform: wifi_signal
    name: ${devicename} WiFi Signal
    id: wifi_signal_db
    entity_category: diagnostic
    device_class: signal_strength
    icon: mdi:wifi
    update_interval: 60s

  - platform: uptime
    name: ${devicename} Uptime
    icon: mdi:clock
    device_class: duration
    update_interval: 60s

  - platform: custom
    lambda: |-
      auto amg = new AMG8833Component();
      App.register_component(amg);
      return {
        amg->sensor_temperature,
        amg->max_temperature,
        amg->min_temperature,
        amg->avg_temperature,
        amg->min_index,
        amg->max_index
      };
    sensors:
      - name: ${devicename} thermal sensor temperature
        device_class: temperature
        unit_of_measurement: "°C"
        accuracy_decimals: 2
      - name: ${devicename} thermal sensor max
        device_class: temperature
        unit_of_measurement: "°C"
        accuracy_decimals: 2
      - name: ${devicename} thermal sensor min
        device_class: temperature
        unit_of_measurement: "°C"
        accuracy_decimals: 2
      - name: ${devicename} thermal sensor avg
        device_class: temperature
        unit_of_measurement: "°C"
        accuracy_decimals: 2
      - name: ${devicename} thermal sensor min index
        accuracy_decimals: 0
      - name: ${devicename} thermal sensor max index
        accuracy_decimals: 0

switch:
  - platform: restart
    name: ${devicename} restart
    device_class: switch
    entity_category: diagnostic
