esphome:
  name: led-matrix
  friendly_name: LED matrix

esp8266:
  board: d1_mini_pro

logger:

api:
  encryption:
    key: "EDlSrcL5Gga4YmDE2XqqEhQqpillDOInt6PKXfogqK4="

ota:
  - platform: esphome
    password: "7569fad8e3af8bf525aa8433726b627c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Led-Matrix Fallback Hotspot"
    password: "sAy13nZTjB6F"

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      entity_category: diagnostic
      icon: mdi:ip-network
    ssid:
      name: ESP Connected SSID
      entity_category: diagnostic
      icon: mdi:wifi
    bssid:
      name: ESP Connected BSSID
      entity_category: diagnostic
      icon: mdi:access-point
    mac_address:
      name: ESP MAC Address
      entity_category: diagnostic
      icon: mdi:chip

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    id: wifi_signal_db
    entity_category: diagnostic
    device_class: signal_strength
    unit_of_measurement: "dBm"
    icon: mdi:wifi

  - platform: uptime
    name: Uptime
    icon: mdi:clock-outline
    device_class: duration
    entity_category: diagnostic

light:
  - platform: neopixelbus
    id: matrice_led
    type: GRB
    variant: WS2812
    pin: GPIO2
    num_leds: 64
    name: "Matrice LED"
    internal: true 

external_components:
  - source: ./custom_components/matrix_display

matrix_display:
  light_id: matrice_led
