esphome:
  name: led_strip_2
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_password_2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led Strip 2 Fallback Hotspot"
    password: "JEJYfHJBSXae"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  local: true

light:
  - platform: neopixelbus
    variant: WS2812
    pin: D6
    num_leds: 30
    type: GRB
    name: "FastLED WS2813 Light 1"
    effects:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks: