substitutions:
  esp_name: my e-ink display #Device Name
  esp_hostname: my-eink-display
  run_time: 5min #can be as long as needed to get data 
  sleep_time: 20min # normal sleep time
  night_sleep_time: 6h # 1st sleep time after midnight
  instance: ""

esphome:
  compile_process_limit: 1
  name: ${esp_hostname}
  includes:
    - localization.h
    - string_size.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "QXQjGMYEQmVpwLZmHQdG3mTKbuu2U3PB9szCjU8oTik="

ota:
  password: "b0960d88ef9cc05659c37f842d619d04"

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_password_2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lilygo-T5 Fallback Hotspot"
    password: "WaVYrTITPfNG"

# deep_sleep:
#   run_duration: ${run_time} 
#   sleep_duration: ${sleep_time}
#   id: deep_sleep_1
#   esp32_ext1_wakeup:
#     pins: GPIO39
#     mode: ALL_LOW

captive_portal:

web_server:
  port: 80
  include_internal: true 

sun:
  latitude: 42.61139°
  longitude: 12.54536°

time:
  - platform: homeassistant
    id: ntp
    timezone: Europe/Rome

external_components:
  # - source: github://ashald/esphome@lilygo-t5-47
  #   components:
  #     - lilygo_t5_47
  # - source:
  #     type: git
  #     url: https://github.com/vbaksa/esphome
  #     ref: dev
  #   components:
  #     - lilygo_t5_47_battery 
  #     - lilygo_t5_47_display
  - source: github://tiaanv/esphome-components
    components:
      - t547
  # - source:
  #     type: git
  #     url: https://github.com/kaweksl/esphome
  #     ref: dev
  #   components:
  #     - lilygo_t5_47_battery 
  #     - lilygo_t5_47_display

# spi:
#   clk_pin: 18
#   mosi_pin: 23

font:
  - file: 
      type: "gfonts"
      family: "Roboto"
      weight: "Medium"
    id: font_footer
    size: 28  
  - file: 
      type: "gfonts"
      family: "Titillium Web"
      weight: "Regular"
    id: font_footer_2
    size: 28  
  - file:
      type: "gfonts"
      family: "Roboto Mono"
      weight: "Regular"
    id: font_value
    size: 24       
  - file:
      type: "gfonts"
      family: "Roboto Mono"
      weight: "Regular"
    id: font_value_big
    size: 96       
  - file:
      type: "gfonts"
      family: "Roboto"
      weight: "Regular"  
    id: font_name
    size: 38
  - file:
      type: "gfonts"
      family: "Titillium Web"
      weight: "Regular"  
    id: font_name_2
    size: 38
  - file: 
      type: "gfonts"
      family: "Roboto Mono"
      weight: "Regular"
    id: font_unit
    size: 28        

    # https://pictogrammers.github.io/@mdi/font/5.3.45/
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_icons
    size: 160
    glyphs:
      - "\U000F0594" # clear-night
      - "\U000F0590" # cloudy
      - "\U000F0595" # partlycloudy
      - "\U000F0591" # fog      
      - "\U000F0592" # hail
      - "\U000F0593" # lightning
      - "\U000F067E" # lightning-rainy
      - "\U000F0596" # pouring
      - "\U000F0597" # rainy
      - "\U000F0F36" # snowy
      - "\U000F067F" # snowy-rainy
      - "\U000F0599" # sunny
      - "\U000F059D" # windy
      - "\U000F059E" # windy-variant
      - "\U000F0F38" # exceptional
      - "\U000F10C2" # thermometer
      - "\U000F054B" # umbrella
      - "\U000F07E4" # CO2
      - "\U000F051F" # hourglass
      - "\U000F024A" # flower
      - "\U000F140B" # flash
      - "\U000F0F31" # night-partly-cloudy 
      - "\U000F0F37" # sunny-alert
      - "\U000F059A" # sunset
      - "\U000F059B" # sunset-down
      - "\U000F059C" # sunset-up
      - "\U000F0A72" # solar-power   
      - "\U000F13E2" # umbrella-closed
      - "\U000F06A5" # power-plug
      - "\U000F1A35" # cloud-percent
      - "\U000F015F" # cloud-black

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_icons_small
    size: 56
    glyphs:
      - "\U000F0594" # clear-night
      - "\U000F0590" # cloudy
      - "\U000F0595" # partlycloudy
      - "\U000F0591" # fog      
      - "\U000F0592" # hail
      - "\U000F0593" # lightning
      - "\U000F067E" # lightning-rainy
      - "\U000F0596" # pouring
      - "\U000F0597" # rainy
      - "\U000F0F36" # snowy
      - "\U000F067F" # snowy-rainy
      - "\U000F0599" # sunny
      - "\U000F059D" # windy
      - "\U000F059E" # windy-variant
      - "\U000F0F38" # exceptional
      - "\U000F10C2" # thermometer
      - "\U000F054B" # umbrella
      - "\U000F07E4" # CO2
      - "\U000F051F" # hourglass
      - "\U000F024A" # flower
      - "\U000F140B" # flash
      - "\U000F0F31" # night-partly-cloudy 
      - "\U000F0F37" # sunny-alert
      - "\U000F059A" # sunset
      - "\U000F059B" # sunset-down
      - "\U000F059C" # sunset-up      
      - "\U000F0A72" # solar-power
      - "\U000F13E2" # umbrella-closed
      - "\U000F06A5" # power-plug
      - "\U000F1A35" # cloud-percent
      - "\U000F015F" # cloud-black

button:
  - platform: restart
    name: "${esp_name} Restart"

  - platform: template
    name: "${esp_name} Refresh"
    icon: "mdi:update"
    on_press:
      then:
      - component.update: t5_display

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO39
      inverted: true
    name: "${esp_name} Button 1"
    on_press:
      then:
       - component.update: t5_display
      
  - platform: gpio
    pin: 
      number: GPIO34
      inverted: true
    name: "${esp_name} Button 2"

  - platform: gpio
    pin: 
      number: GPIO35
      inverted: true
    name: "${esp_name} Button 3"

sensor:
  - platform: homeassistant
    id: sun_elevation
    entity_id: sun.sun
    attribute: elevation

  - platform: sun
    id: esphome_sun_elevation
    type: elevation

  - platform: homeassistant
    entity_id: sensor.openweathermap_cloud_coverage
    id: cloud_perc
    internal: true
    
  - platform: homeassistant
    entity_id: sensor.${instance}owl_intuition_electricity_power
    id: kw_daily
    internal: true

  - platform: homeassistant
    entity_id: sensor.${instance}daily_sensor
    id: kw_daily_in_max
    internal: true

  - platform: homeassistant
    entity_id: sensor.${instance}potenza_generata_massima
    id: kw_daily_out_max
    internal: true

  - platform: homeassistant
    entity_id: sensor.${instance}abb_pout
    id: kw_daily_out
    internal: true
    on_value: # Actions to perform once data for the last sensor has been received
      then:
        - script.execute: all_data_received       

  - platform: adc
    pin: GPIO36
    name: "${esp_name} Battery Voltage"
    id: batt_volt
    attenuation: 11db
    update_interval: 60s
    filters:
      - multiply: 2

  - platform: template
    name: "${esp_name} Battery"
    id: batt
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: battery
    lambda: |-
      int y = (1-(4.1-id(batt_volt).state)/(4.1-3.3))*100;
      if (y < 100) {return y;} else {return 100;};
    update_interval: 60s

  - platform: template
    id: kw_daily_out_perc
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: power
    lambda: |-
      int value = id(kw_daily_out).state/3300*100;
      return value;
    update_interval: 60s

  - platform: template
    id: kw_daily_perc
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: power
    lambda: |-
      int value = id(kw_daily).state/3300*100;
      return value;
    update_interval: 60s

  - platform: template
    id: sun_perc
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      int value = id(esphome_sun_elevation).state/90*100;
      if (value < 0) value = 0;
      return value;
    update_interval: 60s

script:
  - id: all_data_received
    then:
      - component.update: batt_volt
      - component.update: batt
      # - component.update: t5_display
      # - script.execute: enter_sleep     

  # - id: enter_sleep
  #   then:
  #     - if:
  #         condition:
  #           lambda: |- 
  #             auto time = id(ntp).now();
  #             if (!time.is_valid()) { 
  #               return false;
  #             }
  #             return (time.hour < 6); 
  #         then:
  #           - logger.log: "It's nighttime, entering long sleep for ${night_sleep_time}"          
  #           - deep_sleep.enter: 
  #               id: deep_sleep_1 
  #               sleep_duration: ${night_sleep_time}
  #         else:
  #           - logger.log: "It's daytime, entering short sleep for ${sleep_time}"             
  #           - deep_sleep.enter: 
  #               id: deep_sleep_1 
  #               sleep_duration: ${sleep_time}

graph:
  - id: multi_graph
    duration: 12h
    x_grid: 10min
    y_grid: 1.0
    max_value: 100
    min_value: 0
    width: 920
    height: 460
    border: True
    traces:
      - sensor: kw_daily_out_perc
        line_type: SOLID
        line_thickness: 5
      - sensor: cloud_perc
        line_type: DOTTED
        line_thickness: 3
      - sensor: sun_perc
        line_type: DASHED
        line_thickness: 3     

display:
  - platform: t547
    id: t5_display
    rotation: 0
    update_interval: 10min
    lambda: |-
      #define yres 540 
      #define xres 960
      #define x_pad 5 // border padding
      #define y_pad 5 // border padding      
      #define x_orig 20
      #define y_orig 50
      
      it.graph(x_orig, y_orig, id(multi_graph));

      int y = 0;
      it.printf(x_orig+10, y_orig+30, id(font_value), TextAlign::BASELINE_LEFT, "Sun %.1f°", id(sun_elevation).state);
      it.printf(x_orig+10, y_orig+60, id(font_value), TextAlign::BASELINE_LEFT, "Clo %.1f%%", id(cloud_perc).state);
      it.printf(x_orig+10, y_orig+90, id(font_value), TextAlign::BASELINE_LEFT, "Pow %.0fw", id(kw_daily_out).state);
      it.print(xres/2, y+y_pad-10, id(font_name_2), TextAlign::TOP_CENTER, generateDateFormat(id(ntp).now()).c_str());
      it.strftime(x_pad, yres-y_pad/2, id(font_footer), TextAlign::BASELINE_LEFT, "Aggiornato: %H:%M", id(ntp).now());
      it.printf(xres-x_pad, yres-y_pad/2, id(font_footer), TextAlign::BASELINE_RIGHT, "%.2fV/%.0f%%", id(batt_volt).state, id(batt).state);
